name: example
description: Demonstrates how to use the plugin_screeb plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_screeb:
    path: ../../packages/sdk-flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
