plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'app.screeb.example'
    compileSdk 35

    defaultConfig {
        applicationId 'app.screeb.example'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'

        manifestPlaceholders = [
                screebChannelId: '0e2b609a-8dce-4695-a80f-966fbfa87a88',
        ]
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'app.screeb.sdk:survey:4.0.1'
}
