name: Publish @screeb/sdk-angular

on:
  push:
    tags:
      - 'sdk-angular/v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --workspace=packages/sdk-angular
      - run: npm publish --workspace=packages/sdk-angular --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
