name: Publish @screeb/react-native

on:
  push:
    tags:
      - '@screeb/react-native@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm install --ignore-scripts
      - run: npm run build --workspace=packages/sdk-reactnative
      - run: npm publish --workspace=packages/sdk-reactnative --access public --provenance
