name: Publish @screeb/sdk-browser

on:
  push:
    tags:
      - 'sdk-browser/v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --ignore-scripts
      - run: npm run versions:check
      - run: npm run release:check --workspace=packages/sdk-browser
      - run: npm publish --workspace=packages/sdk-browser --access public --provenance
